
import { Inter } from "next/font/google";
import "./globals.css";
import CustomLink from "./components/CustomLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <>
          <nav className="">
            <ul className="flex gap-5 my-5 p-4">
              <li><CustomLink path="/">Home</CustomLink></li>
              <li><CustomLink path="/dashboard/analytics">Analytics</CustomLink></li>
              <li><CustomLink prefetch={false}  path="/dashboard/settings">Settings</CustomLink></li>
              <li><CustomLink prefetch={false}  path="/heavy">Heavy</CustomLink></li>
            </ul>

          </nav>

        </>

        {children}</body>
    </html>
  );
}
